module.exports.GENERAL = {
  SUCCESS: 200,
  ERROR: -200,
  NOT_AUTHENTICATED: 400
};

module.exports.ORDER = {
  HAS_PENDING_ORDER: 98,
  STATUS_PENDING: 99,
  STATUS_ACCEPTED: 100,
  STATUS_DELIVERING: 101,
  STATUS_COMPLETED: 102,
  STATUS_CANCELED: -100
};